### ISSUE TITLE
Unhandled rejection Error - Sometimes - on Retweet

### ISSUE THREAD

**Issue by cucrecords** [spences10/twitter-bot-bootstrap#158]
Hi, love the bot... works great and I've been able to customize it to interact with Microsoft's QnA. However, every now and then I get the following error message on Retweets:

Unhandled rejection Error: Twit: Params object is missing a required parameter for this request: `id`

Not sure if that's a twit module problem or the twitter-bot. I can't seem to make it go away or figure out why the id param is missing.

This doesn't happen on all retweets... which is even more confusing...

More confusing is that I get Errorderp: Retweet! and then Success and the tweet... but it doesn't post to Twitter.

I'm running the bot currently from cloud9, npm v8.9.1, twit v2.2.9

**Comment by spences10** [comment]
Hi @cucrecords 

I'm going to guess that is because the tweet doesn't exist anymore - the bot uses a search function which I have never really found that accurate in my experience.

If you really want to find the issue add in some `console.log`'s around where you see the issue happening and try to identify what's going on.

I'm going to guess that you'll have `undefined` for the tweet id when doing so

I'd suggest taking a look at https://github.com/spences10/delay-tweet which uses `stream` where you can add a slight delay before retweeting off of the twirtter live streeam.

I'm interested in your bots interaction with MS QnA, do you have an example on GitHub I could check out?

**Comment by cucrecords** [comment]
Hi @spences10, thanks for the feedback that makes sense. My initial logging does bring back an id for the tweets that error, but it's 1380000 every time regardless of the tweet... which looks maybe like an error code ID possibly. I'll keep looking into it, but it's not a critical problem. Should we close this issue and rack it up to the twitter api search functionality?

I'll try to get my code up on GitHub shortly 👍 and I'll let you know. {need to obfuscate the keys to Microsoft's QnA} - also... I'm a hack coder so it's very copy pasta :).

**Comment by spences10** [comment]
I'm a professional copy pasta 💪 😁 

Take a look at `dotenv` for hiding environment variables 👍 

It's used in this repo 

I'll close this but please provide details on your bit when you get it into GitHub, please feel free to log any more issues also [ask me anything](https://github.com/spences10/ama) or get me on Twitter @ScottDevTweets
