### ISSUE TITLE
Random replies syntax error

### ISSUE THREAD

**Issue by nocean** [spences10/twitter-bot-bootstrap#81]
Hi Scott,

Found a little issue with the Readme. The syntax given for the RANDOM_REPLY var is shown as separated with commas, just like the QUERY_STRING var above it. However, after this failing to work I noticed that on [line 6 of reply.js](https://github.com/spences10/twitter-bot-bootstrap/blob/master/src/api/reply.js#L6), the split is defined with a pipe |, not a comma. I think this is an intelligent choice, as it's likely you might want a comma in your reply string, but that means in the Readme, this:

`RANDOM_REPLY=Hi @${screenName} thanks for the follow! What are you working on today?,@${screenName} thanks for following! What are you working on today?`

Should be:

`RANDOM_REPLY=Hi @${screenName} thanks for the follow! What are you working on today?|@${screenName} thanks for following! What are you working on today?`

**Comment by spences10** [comment]
Hey @nocean,

I'm more than happy to accept a PR if you want to contribute my friend 😄 

I'm about to do some changes for the retweet part [which is basically all of it now as thats the only thing Twitter hasn't banned] where instead of using a search on a timer with intervals the bot will use a sream for thw tweets and retweet those.

There's a couple of moving parts so will probably go in stages, it will involve adding tweets to a database and comparing against the db before re-Tweeting

The pipes are used in the config of my other [bot](https://github.com/spences10/twitter-bot-twit) which is what will [eventually] be coming to this bootstrap

Thanks again for taking the time to check out the repo and I hope you have found it useful. 👍 

Let me know if that answers your question and I'll close the issue if so, thanks.

**Comment by nocean** [comment]
Hi @spences10, good point -- I just read up on Twitter's policies and see that following is not sufficient for allowing an auto-reply. No point at all to fix that if it's going to be removed.

**Comment by spences10** [comment]
Oh! Do you have a link for it?

Looks like this bootstrap isn't going to end up doing much for very longer 🙃

**Comment by nocean** [comment]
Here's a [link](https://support.twitter.com/articles/76915).

Under:
B. Automated Tweets -> 2. Posting automated mentions and replies

I think retweets are still fine though, which I think is the biggest purpose for this bootstrap, imo. Or is Twitter getting sticky about those too?

**Comment by spences10** [comment]
Bah!

I think there is certain areas where there needs to be an opt in for things like this but yes, it seems like Twitter is tightening up on this 😢
