### ISSUE TITLE
Follower reply functionality triggers on wrong event

### ISSUE THREAD

**Issue by pabrams** [spences10/twitter-bot-bootstrap#99]
The string configured in RANDOM_REPLY in the .env file is being tweeted by my bot at its own account, for some reason.  I can't tell what the exact trigger is - I thought it was when I followed someone else, but it doesn't seem to always trigger when I do that.  It's definitely not triggering on someone else following me, because I haven't gained any new followers, yet the tweet is appearing.

**Comment by pabrams** [comment]
I'm no longer able to reproduce this.  Will leave it open a while longer.

**Comment by spences10** [comment]
Hi @pabrams, 

Apologies I have only come across this issue raised today, I must have missed it somehow! 🙃 

Ok, best thing for diagnosing the follower event is to open a separate twitter account for this sort of testing then follow the bot account you will be able to see it triggered real time 👍 

Let me know if your still having issues, otherwise I shall close this

Thanks 👍

**Comment by spences10** [comment]
Tested, functioning as expected, closing, let me know if you still have issues with this @pabrams
